### PR TITLE
add `option` argument to AddWeakMapping (Closes #112)

### PR DESCRIPTION
**Pull request by eloytoro**
Alternative to #112

### CODE REVIEW

**Comment by svermeulen** [comment]
Was there a reason you didn't also make the black hole bindings buffer local?  From reading the code I think that the default substitute map for `s` and `S` will no longer work when `g:EasyClipUseSubstituteDefaults` is set

**Comment by eloytoro** [comment]
no real reason, if required i can create a PR for it

**Comment by eloytoro** [comment]
that would make it so _all_ of the weak mappings are set by buffer, so no parameter would be needed.
Is that something you'd like?

**Comment by svermeulen** [comment]
Yeah I think that makes the most sense, so one more PR there would be great  :)

**Pull request merged**
