### PR TITLE
Feature/shared yanks

### PR DESCRIPTION
**Pull request by faceleg**
Love the plugin, thanks for your work.

Only thing I miss from YankRing is shared history. This is my initial attempt at adding it.

Let me know what you want changed?

### CODE REVIEW

**Comment by svermeulen** [comment]
I didn't even consider this as a feature but would definitely be cool.  I've installed it and going to play with it a bit more before merging

I found at least one issue:  EasyClip#Yank#SaveSharedYanks needs to be called at the end of EasyClip#Yank#YankMotion.  Easy fix though.

Thanks!

**Comment by faceleg** [comment]
That's done.

I couldn't find where I need to add `EasyClip#Yank#SaveSharedYanks` in order to make shared history work with the `mm` binding - do you have any ideas?

**Comment by svermeulen** [comment]
I love how this also gives us a persistent yank history when closing and re-opening vim as well.

Yep I know what needs to be done with the `mm` command, going to refactor a bit to address that one.

One thing that concerns me is that it appears to be reading from file for every paste.  I can imagine a complex macro that, when executed with a count, ends up reading from file thousands of times in a row.  I wonder if we could change it to check the file modification date and not bother re-reading in that case?   We could also store the new modification date on write so we don't bother reading our own changes back

**Comment by faceleg** [comment]
I work on multiple projects that share code (copy paste style sharing :facepunch:) being able to yank/paste between vim instances is really wonderful!

Agree on file modification time, I'll look into this when I can, hopefully today or tomorrow.

**Comment by svermeulen** [comment]
Ok great - I'll fix the issues with 'm' commands

**Comment by faceleg** [comment]
That should do it.

**Comment by svermeulen** [comment]
Yep that makes sense as an option. 

I merged in all your changes and made a bunch of tweaks/fixes.  They are all in the 'develop' branch which I'm going to play with for a few days before merging in to master.  (I also have to update the documentation first)

Big change I made is that you now have to call the command 'EasyClipOnYanksChanged' after touching the yank buffer, so it can save it to file.  I'm pretty sure I updated every different case to properly load and properly save but going to test a bit more to be sure

This is a great feature, thanks  :D

**Comment by svermeulen** [comment]
Merged into master

**Comment by faceleg** [comment]
:dancer:

**Pull request closed without merging**
